//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Creator
{


    public partial class Browse
    {

        /// <summary>
        /// SearchBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox SearchBox;

        /// <summary>
        /// DropDownSort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DropDownSort;

        /// <summary>
        /// SearchCreator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SearchCreator;

        /// <summary>
        /// RepeaterCreator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater RepeaterCreator;

        /// <summary>
        /// RepeaterProject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater RepeaterProject;
    }
}
