//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Creator
{


    public partial class Home
    {

        /// <summary>
        /// WelcomeMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl WelcomeMessage;

        /// <summary>
        /// Notifications control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Notifications;

        /// <summary>
        /// AccountIcon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image AccountIcon;

        /// <summary>
        /// lblUsername control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUsername;

        /// <summary>
        /// lblFullname control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblFullname;

        /// <summary>
        /// divEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell divEmail;

        /// <summary>
        /// lblEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEmail;

        /// <summary>
        /// lblDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDate;

        /// <summary>
        /// RepeaterTimeline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater RepeaterTimeline;

        /// <summary>
        /// msgEmpty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl msgEmpty;
    }
}
