//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Creator.Projects.Updates
{


    public partial class Edit
    {

        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// TextBoxUpdate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBoxUpdate;

        /// <summary>
        /// lblDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDate;

        /// <summary>
        /// txtDesc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDesc;

        /// <summary>
        /// FileImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl FileImage;

        /// <summary>
        /// FileVideo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl FileVideo;

        /// <summary>
        /// FilePDF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl FilePDF;

        /// <summary>
        /// FileText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl FileText;

        /// <summary>
        /// FileTextContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FileTextContent;

        /// <summary>
        /// FileZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl FileZip;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSubmit;

        /// <summary>
        /// btnDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnDelete;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>
        /// RadioPublic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RadioPublic;

        /// <summary>
        /// RadioPrivate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// 
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RadioPrivate;
    }
}
